# Generated by Django 4.1.7 on 2023-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
