# Generated by Django 4.1.7 on 2023-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_twitteraccount_account_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitterthread',
            options={'verbose_name': 'Twitter Thread', 'verbose_name_plural': 'Twitter Threads'},
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='emojis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='hashtags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='mentions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='num_tweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='replies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='retweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='sentiment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='tweet_length',
            field=models.TextField(null=True),
        ),
    ]
