# Generated by Django 4.1.7 on 2023-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_twitterthread_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterthread',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
