# Generated by Django 4.1.7 on 2023-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_twitterthread_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='follower_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='following_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
