# Generated by Django 4.1.7 on 2023-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_twitteraccount_follower_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='last_tweet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
