# Generated by Django 4.1.7 on 2023-03-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_twitteraccount_last_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='rate_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitterthread',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
