# Generated by Django 4.1.7 on 2023-03-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_twitteraccount_rate_limit_twitterthread_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='twitterthread',
            unique_together=set(),
        ),
    ]
