# Generated by Django 4.1.7 on 2023-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_twitterthread_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
